name: oo-mysql-5-7
title: OO MySql for Docs
version: "0.1"
summary: "empty summary"
description: "empty description"
icon: icons/asc-de-256.png
grade: stable
confinement: strict
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

layout:
  /etc/my.cnf:
    bind-file: $SNAP_DATA/etc/my.cnf
  /etc/my.cnf.d:
    bind: $SNAP_DATA/etc/my.cnf.d
  /usr/bin/python:
    bind-file: $SNAP/usr/bin/python2.7
  /usr/bin/wget:
    bind-file: $SNAP/usr/bin/wget
  /usr/lib/x86_64-linux-gnu/libpsl.so.5:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libpsl.so.5.3.2
  /etc/wgetrc:
    bind-file: $SNAP/etc/wgetrc

lint:
  ignore:
    - classic

environment:
  HOME: $SNAP_DATA
  OPENSSL_CONF: /dev/null

apps:
  # MySQL daemon
  mysql:
    command: bin/start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  
  # MySQL client
  mysql-client:
    command: bin/run-mysql
    plugs: [network, network-bind]

  mysqldump:
    command: bin/mysqldump --lock-tables onlyoffice
    plugs: [network, network-bind]

hooks:
  configure:
    plugs: [network, network-bind, account-control, gpg-keys, accounts-service, system-observe] #system-files, 

  install:
    plugs: [network, network-bind, removable-media, desktop, unity7]

  pre-refresh:
    plugs: [network, network-bind, removable-media, desktop, unity7]

  post-refresh:
    plugs: [network, network-bind, removable-media, desktop, unity7]

parts:
  boost:
    plugin: dump
    source: https://github.com/kyrofa/boost_tarball/raw/master/boost_1_59_0.tar.gz
    stage:
      - boost/
    prime:
      - -*

  mysql:
    plugin: cmake
    source: https://github.com/mysql/mysql-server.git
    source-tag: mysql-5.7.27
    source-depth: 1
    override-pull: |
      craftctl default
    after: [boost, patches]
    cmake-parameters:
      - -WITH_LIBWRAP=ON
      - -DMYSQL_TCP_PORT=3306
      - -DWITH_BOOST=$CRAFT_STAGE
      - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
      - -DCMAKE_INSTALL_PREFIX=/
      - -DBUILD_CONFIG=mysql_release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_EMBEDDED_SERVER=OFF
      - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
      - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
      - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
      - -DWITH_PARTITION_STORAGE_ENGINE=OFF
      - -DINSTALL_MYSQLTESTDIR=
    stage-packages:
      - libaio1t64
    build-packages:
      - wget
      - g++
      - cmake
      - bison
      - libncurses-dev
      - libaio-dev
      - libtirpc-dev
      - libtirpc3t64
      - pkg-config
    stage:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server
      - -COPYING
    prime:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server

      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/myisam*
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress

  mysql-customizations:
    plugin: dump
    source: src/mysql/

  patches:
    source: src/patches
    plugin: dump
    prime:
      - -*
  common:
    plugin: dump
    source: src/common/
